baseURL = 'https://adevlin780a.github.io/portfolio/'
languageCode = 'en-us'
title = 'Andrew Devlin'
theme = 'hugo-resume'
relativeURLs = true
uglyURLs = false  


[params]
email = "a.devlin780@gmail.com"
favicon = "favicon.ico"
firstName = "Andrew"
lastName = "Devlin"
profileImage = "profile.jpg"
sections = ["creations", "skills", "experience", "education"]
